name: 'Julia package butler'
description: 'This action performes maintainance tasks on a Julia package repository.'
author: 'David Anthoff'
inputs:
  github-token:
    required: true
  ssh-private-key:
    required: true
  channel:
    required: true
runs:
  using: 'node16'
  main: 'lib/main.js'
